<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="Sanju" failures="1" tests="3" name="Test(failed)" time="0.046" errors="0" timestamp="2024-11-13T07:26:51 IST">
  <testcase classname="TestNG.ex9_Sample2" name="TC6" time="0.014">
    <failure type="java.lang.AssertionError" message="Failed TC6: both Results are diff expected [xyz] but found [abcd]">
      <![CDATA[java.lang.AssertionError: Failed TC6: both Results are diff expected [xyz] but found [abcd]
at TestNG.ex9_Sample2.TC6(ex9_Sample2.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TC6 -->
  <testcase classname="TestNG.ex9_Sample2" name="TC5" time="0.002"/>
  <testcase classname="TestNG.ex9_Sample1" name="TC3" time="0.0"/>
  <testcase classname="TestNG.ex9_Sample2" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
  <testcase classname="TestNG.ex9_Sample1" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG.ex9_Sample1" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
</testsuite> <!-- Test(failed) -->
